### ISSUE TITLE
Improvement - requirements.txt

### ISSUE THREAD

**Issue by oguzsh** [onlyfryou/instaPY#1]
Hi @onlyfryou ✌️

I think you should add "requirements.txt" because if a developer wants to work on the python side, they can't know which packages to install, that's why you should add.

Have a nice day 🌹

**Comment by onlyfryou** [comment]
All right because ı haven't enough time for this. First mission add
requirments.txt. Thanks for reminding bro 🥰🥰🥰

25 Tem 2020 Cmt 23:22 tarihinde Oguzhan İnce <notifications@github.com>
şunu yazdı:
